### ISSUE TITLE
500 Internal Server Error - Redmine 3.0

### ISSUE THREAD

**Issue by KeyTrap** [MadEgg/redmine_planning#30]
Redmine 3.0 - 500 Internal Server Error after click on PLAN button.

--
Processing by PlanningController#show as HTML
  Parameters: {"project_id"=>"aktualizacje-drupal"}
  Current user: Admin (id=1)
  Rendered queries/_filters.html.erb (6.2ms)
  Rendered plugins/redmine_planning/app/views/planning/show.html.erb within layouts/base (10.1ms)
Completed 500 Internal Server Error in 36ms

ActiveRecord::RecordNotFound (Couldn't find Tracker with 'id'=all):
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:336:in `raise_record_not_found_exception!'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:456:in `find_one'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:435:in `find_with_ids'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:71:in `find'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:3:in `find'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/core.rb:130:in `find'
  plugins/redmine_planning/app/views/planning/show.html.erb:87:in `block in _plugins_redmine_planning_app_views_planning_show_html_erb___3019745381629332982_75232560'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.2.0/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.2.0/lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.2.0/lib/action_view/helpers/capture_helper.rb:38:in `capture'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.2.0/lib/action_view/helpers/capture_helper.rb:152:in `content_for'
  plugins/redmine_planning/app/views/planning/show.html.erb:57:in `_plugins_redmine_planning_app_views_planning_show_html_erb___3019745381629332982_75232560'
--

Configuration:
Environment:
  Redmine version                3.0.1.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  recurring_tasks                1.3.0
  redirect_to_after_login        0.0.2
  redmine_planning               0.7.6
  timelog_timer                  2.0.0

**Comment by knvmmohan** [comment]
Same issue for me...

**Comment by Helvehammer** [comment]
I've made some changes and it works on Redmine 3.0.2.stable.

FILE: redmine_planning\app\controllers\planning_controller.rb
Line 119:
WAS:		projects = Project.find(:all)
CHANGED TO:	projects = Project.all

Line 131:
WAS:		trackers = Tracker.find(:all)
CHANGED TO:	trackers = Tracker.all

Line 143:
WAS:		versions = Version.find(:all)
CHANGED TO:	versions = Version.all

FILE: redmine_planning\app\views\planning\show.html.erb
Line 87:
WAS:		tracker_list= Tracker.find(:all)
CHANGED TO:	tracker_list= Tracker.all

FILE: redmine_planning\app\views\planning\_planning_settings.html.erb
Line 79:
WAS:		<% Tracker.find(:all).each do |tracker| %>
CHANGED TO:	<% Tracker.all.each do |tracker| %>

**Comment by hhschmidt** [comment]
@Helvehammer: May I ask if the mentioned modifications are really all you had to do to get it going on 3.0.2-stable. Or was there other stuff you also had to tweak - anything ...?
Reason I am asking is that I am having trouble to use this plugin on redmine 3.0.3
(see my report in [issue 31](https://github.com/MadEgg/redmine_planning/issues/31) ). 
* I did apply all your changes as reported above (thanks for the precise description) - but that did not solve my problem.
* I have also removed all other plugins ... but this did not help either

Can you think of any other possible reason for my problem?
Thanks for your consideration.

**Comment by dziustino** [comment]
Environment:
  Redmine version                3.0.1.stable.14180
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.9.5
  Filesystem                     
  Xitolite                       1.7.9.5
Redmine plugins:
  progressive_projects_list      2.0.1
  redmine_agile                  1.3.8
  redmine_bootstrap_kit          0.2.3
  redmine_checklists             3.0.4
  redmine_dmsf                   1.5.1 stable
  redmine_git_hosting            1.0.4
  redmine_planning               0.7.6

This fix works for me.
@Helvehammer try to restart redmine after editing files
Linux: touch /path/to/redmine/tmp/restart.txt

**Comment by dziustino** [comment]
@hhschmidt also try to clear redmine cache

```
cd /path/to/redmine/
rake tmp:cache:clear
rake tmp:sessions:clear
touch /path/to/redmine/tmp/restart.txt
````
